HOTSPOT_SSID=INJECT_HOSTNAME
HOTSPOT_PASSWORD=linux-hotspot
HOTSPOT_NETWORK_BAND=bg
HOTSPOT_NETWORK_INTERFACE=wlan0
HOTSPOT_NETWORK_INTERFACE_FALLBACK_1=wlo1
HOTSPOT_HEALTHCHECK_TARGET=8.8.8.8
SYSTEM_DISABLE_SLEEP_LIKE=true
SYSTEM_ENABLE_PERFORMANCE_MODE=false